server:
  port: 8081
spring:
  application:
    name: s-matadi

  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: s-matadi
      authentication-database: admin
      port: 27017